### PR TITLE
Fixes #121

### LINKED ISSUE #121: Check for Positron
In addition to [checking for RStudio](https://github.com/mlverse/pysparklyr/blob/39748e1b0bf1f6e9a82b490ccd1ec37d2ecef235/R/sparklyr-spark-connect.R#L242-L262), `pysparklyr` should also check for and include details about Positron if that is the IDE being used.

### PR DESCRIPTION
**Pull request by edgararuiz**
- Adds Positron IDE check for the User Agent
- Includes the Positron version
- Adds tests, NEWS item, and bumps version to dev

### CODE REVIEW

**Comment by edgararuiz** [comment]
Fixes #121 

To test, in Positron use:

```r
> pak::pak("mlverse/pysparklyr@updates")
                                                                           
ℹ No downloads are needed
✔ 1 pkg + 61 deps: kept 56 [1.1s]
> pysparklyr:::build_user_agent()
sparklyr/1.8.6 posit-positron/2024.07.0
```

**Comment by edgararuiz** [comment]
@blairj09 - The PR is ready if you'd like to take a look

**Comment by edgararuiz** [comment]
cc'ing @atheriel

**Comment by jthomasmock** [comment]
Working for me locally!

```r
build_user_agent()
sparklyr/1.8.6 posit-positron/2024.07.0
```

```r
> build_user_agent()
sparklyr/1.8.6 posit-rstudio/2024.07.0+330
```

I've asked the Positron dev team about whether we can expose more metadata beyond just the pure calendar versioning+patch `2024.07.0` rather than including build info or other info `2024.07.0+330`.

**Pull request merged**
